SummerCamp/Models/TeamSponsorViewModel.cs
using SummerCamp.DataModels.Models;

namespace SummerCamp.Models
{
    public class TeamSponsorViewModel
    {
        public int Id { get; set; }

        public int? TeamId { get; set; }

        public int? SponsorId { get; set; }

        public virtual Sponsor? Sponsor { get; set; }

        public virtual Team? Team { get; set; }
    }
}

SummerCamp/Controllers/TeamSponsorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SummerCamp.DataAccessLayer.Interfaces;
using SummerCamp.DataModels.Models;
using SummerCamp.Models;

namespace SummerCamp.Controllers
{
    public class TeamSponsorController : Controller
    {
        private readonly ITeamSponsorRepository _teamSponsorRepository;
        private readonly ISponsorRepository _sponsorRepository;
        private readonly ITeamRepository _teamRepository;
        private readonly IMapper _mapper;
        public TeamSponsorController(ITeamSponsorRepository teamSponsorRepository, ISponsorRepository sponsorRepository, ITeamRepository teamRepository, IMapper mapper)
        {
            _teamSponsorRepository = teamSponsorRepository;
            _sponsorRepository = sponsorRepository;
            _teamRepository = teamRepository;
            _mapper = mapper;
        }

        public IActionResult Index(TeamSponsorViewModel teamSponsorViewModel)
        {
            var teamSponsor = _teamSponsorRepository.GetAll();
            var teamSponsorModels = _mapper.Map<IList<TeamSponsorViewModel>>(teamSponsor);
            return View(teamSponsorModels);
        }

        public IActionResult Add()
        {
            ViewData["Teams"] = new SelectList(_teamRepository.GetAll(), "Id", "Name");
            ViewData["Sponsors"] = new SelectList(_sponsorRepository.GetAll(), "Id", "Name");

            return View();
        }

        [HttpPost]
        public IActionResult Add(TeamSponsorViewModel teamSponsorViewModel)
        {
            if (ModelState.IsValid)
            {
                _teamSponsorRepository.Add(_mapper.Map<TeamSponsor>(teamSponsorViewModel));
                _teamSponsorRepository.Save();
                return RedirectToAction("Index");
            }

            return View(teamSponsorViewModel);
        }

        public IActionResult Edit(int coachId)
        {
            var teamSponsor = _teamSponsorRepository.GetById(coachId);
            ViewData["Teams"] = new SelectList(_teamRepository.GetAll(), "Id", "Name");
            ViewData["Sponsors"] = new SelectList(_sponsorRepository.GetAll(), "Id", "Name");

            var result = _mapper.Map<TeamSponsorViewModel>(teamSponsor);
            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(TeamSponsorViewModel teamSponsorViewModel)
        {
            if (ModelState.IsValid)
            {
                _teamSponsorRepository.Update(_mapper.Map<TeamSponsor>(teamSponsorViewModel));
                _teamSponsorRepository.Save();
                return RedirectToAction("Index");
            }

            return View(teamSponsorViewModel);
        }

        public IActionResult Delete(int teamSponsorId)
        {
            var teamSponsor = _teamSponsorRepository.GetById(teamSponsorId);
            _teamSponsorRepository.Delete(teamSponsor);
            _teamSponsorRepository.Save();
            return RedirectToAction("Index");
        }
    }
}

SummerCamp/Views/TeamSponsor/Add.cshtml
@using SummerCamp.Models

@model TeamSponsorViewModel

<form id="myForm" asp-action="Add" method="post" class="needs-validation" asp-controller="TeamSponsor" novalidate>
    <div class="form-group">
        <label asp-for="TeamId" class="control-label"></label>
        @Html.DropDownList("TeamId", (IEnumerable<SelectListItem>) ViewData["Teams"], "Select a team", new { @class = "form-control" })
        <span asp-validation-for="TeamId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="SponsorId" class="control-label"></label>
        @Html.DropDownList("SponsorId", (IEnumerable<SelectListItem>) ViewData["Sponsors"], "Select a sponsor", new { @class = "form-control" })
        <span asp-validation-for="SponsorId" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

SummerCamp/Views/TeamSponsor/Edit.cshtml
@using SummerCamp.Models

@model TeamSponsorViewModel

<form id="myForm" asp-action="Add" method="post" class="needs-validation" asp-controller="TeamSponsor" novalidate>
    <input asp-for="Id" class="form-control" hidden />
    <div class="form-group">
        <label asp-for="TeamId" class="control-label"></label>
        @Html.DropDownList("TeamId", (IEnumerable<SelectListItem>) ViewData["Teams"], "Select a team", new { @class = "form-control" })
        <span asp-validation-for="TeamId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="SponsorId" class="control-label"></label>
        @Html.DropDownList("SponsorId", (IEnumerable<SelectListItem>) ViewData["Sponsors"], "Select a sponsor", new { @class = "form-control" })
        <span asp-validation-for="SponsorId" class="text-danger"></span>
    </div>


    <button type="submit" class="btn btn-primary">Create</button>
</form>

SummerCamp/Views/TeamSponsor/Index.cshtml
@using SummerCamp.Models
@model IEnumerable<TeamSponsorViewModel>
@{
    ViewData["Title"] = "Team Sponsors";
}
<h1 class="centered-title">Team Sponsors</h1>
<a asp-controller="TeamSponsor" asp-action="Add" class="btn btn-primary">Add sponsor to team</a>
<div class="text-center">
    <div class="table-responsive">
        <table class="table table-bordered table-condensed table-striped table-hover sortable">
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="6">No Records found.</td>
                </tr>
            }
            else
            {
                <thead class="thead-dark">
                    <tr>
                        <th>Team</th>
                        <th>Sponsor</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Team</td>
                            <td>@item.Sponsor</td>
                            <td>
                                <a asp-action="Edit" asp-controller="TeamSponsor" asp-route-teamsponsorId="@item.Id" class="btn btn-primary">
                                    Edit
                                </a>
                                <a asp-action="Delete" asp-controller="TeamSponsor" asp-route-teamsponsorId="@item.Id" class="btn btn-primary">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            }
        </table>
    </div>
</div>