SummerCamp/Controllers/CoachesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SummerCamp.DataAccessLayer.Interfaces;
using SummerCamp.DataModels.Models;
using SummerCamp.Models;

namespace SummerCamp.Controllers
{
    public class CoachesController : Controller
    {
        private readonly ICoachRepository _coachRepository;
        private readonly IMapper _mapper;
        public CoachesController(ICoachRepository coachRepository, IMapper mapper)
        {
            _coachRepository = coachRepository;
            _mapper = mapper;
        }

        public IActionResult Index(CoachViewModel coachViewModel)
        {
            var coaches = _coachRepository.GetAll();
            var coachModels = _mapper.Map<IList<CoachViewModel>>(coaches);
            return View(coachModels);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(CoachViewModel coachViewModel)
        {
            if (ModelState.IsValid)
            {
                _coachRepository.Add(_mapper.Map<Coach>(coachViewModel));
                _coachRepository.Save();
                return RedirectToAction("Index");
            }

            return View(coachViewModel);
        }

        public IActionResult Edit(int coachId)
        {
            var coach = _coachRepository.GetById(coachId);
            var result = _mapper.Map<CoachViewModel>(coach);
            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(CoachViewModel coachViewModel)
        {
            if (ModelState.IsValid)
            {
                _coachRepository.Update(_mapper.Map<Coach>(coachViewModel));
                _coachRepository.Save();
                return RedirectToAction("Index");
            }

            return View(coachViewModel);
        }

        public IActionResult Delete(int coachId)
        {
            var coach = _coachRepository.Get(x => x.Id == coachId).FirstOrDefault();
            if (coach != null)
            {
                foreach (var team in coach.Teams)
                {
                    team.CoachId = null;
                }
                _coachRepository.Delete(coach);
                _coachRepository.Save();
            }
            return RedirectToAction("Index");
        }
    }
}

SummerCamp/Controllers/PlayerController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SummerCamp.DataAccessLayer.Interfaces;
using SummerCamp.DataModels.Models;
using SummerCamp.Models;

namespace SummerCamp.Controllers
{
    public class PlayerController : Controller
    {
        private readonly IPlayerRepository _playerRepository;
        private readonly ITeamRepository _teamRepository;
        private readonly IMapper _mapper;
        public PlayerController(IPlayerRepository playerRepository, ITeamRepository teamRepository, IMapper mapper)
        {
            _playerRepository = playerRepository;
            _teamRepository = teamRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var players = _playerRepository.GetAll();

            var playerModels = _mapper.Map<IList<PlayerViewModel>>(players);

            return View(playerModels);
        }

        public IActionResult Add()
        {
            ViewData["Teams"] = new SelectList(_teamRepository.GetAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Add(PlayerViewModel playerViewModel)
        {
            if (ModelState.IsValid)
            {
                _playerRepository.Add(_mapper.Map<Player>(playerViewModel));
                _playerRepository.Save();
                return RedirectToAction("Index");
            }

            return View(playerViewModel);
        }

        public IActionResult Edit(int playerId)
        {
            var player = _playerRepository.GetById(playerId);
            ViewData["Teams"] = new SelectList(_teamRepository.GetAll(), "Id", "Name");
            return View(_mapper.Map<PlayerViewModel>(player));
        }
        [HttpPost]
        public IActionResult Edit(PlayerViewModel playerViewModel)
        {
            if (ModelState.IsValid)
            {
                _playerRepository.Update(_mapper.Map<Player>(playerViewModel));
                _playerRepository.Save();
                return RedirectToAction("Index");
            }

            return View(playerViewModel);
        }

        public IActionResult Delete(int playerId)
        {
            var player = _playerRepository.GetById(playerId);
            _playerRepository.Delete(player);
            _playerRepository.Save();
            return RedirectToAction("Index");
        }
    }
}

SummerCamp/Controllers/SponsorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SummerCamp.DataAccessLayer.Interfaces;
using SummerCamp.DataModels.Models;
using SummerCamp.Models;

namespace SummerCamp.Controllers
{
    public class SponsorController : Controller
    {
        private readonly ISponsorRepository _sponsorRepository;
        private readonly IMapper _mapper;
        public SponsorController(ISponsorRepository sponsorRepository, IMapper mapper)
        {
            _sponsorRepository = sponsorRepository;
            _mapper = mapper;
        }

        public IActionResult Index(SponsorViewModel sponsorViewModel)
        {
            var sponsors = _sponsorRepository.GetAll();
            var sponsorModels = _mapper.Map<IList<SponsorViewModel>>(sponsors);
            return View(sponsorModels);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(SponsorViewModel sponsorViewModel)
        {
            if (ModelState.IsValid)
            {
                _sponsorRepository.Add(_mapper.Map<Sponsor>(sponsorViewModel));
                _sponsorRepository.Save();
                return RedirectToAction("Index");
            }

            return View(sponsorViewModel);
        }

        public IActionResult Edit(int sponsorId)
        {
            var sponsor = _sponsorRepository.GetById(sponsorId);
            return View(_mapper.Map<SponsorViewModel>(sponsor));
        }
        [HttpPost]
        public IActionResult Edit(SponsorViewModel sponsorViewModel)
        {
            if (ModelState.IsValid)
            {
                _sponsorRepository.Update(_mapper.Map<Sponsor>(sponsorViewModel));
                _sponsorRepository.Save();
                return RedirectToAction("Index");
            }

            return View(sponsorViewModel);
        }

        public IActionResult Delete(int sponsorId)
        {
            var sponsor = _sponsorRepository.GetById(sponsorId);
            _sponsorRepository.Delete(sponsor);
            _sponsorRepository.Save();
            return RedirectToAction("Index");
        }
    }
}

SummerCamp/Controllers/TeamController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SummerCamp.DataAccessLayer.Interfaces;
using SummerCamp.DataModels.Models;
using SummerCamp.Models;

namespace SummerCamp.Controllers
{
    public class TeamController : Controller
    {
        private readonly ITeamRepository _teamRepository;
        private readonly ICompetitionTeamRepository _competitionTeamRepository;
        private readonly ISponsorRepository _sponsorRepository;
        private readonly IPlayerRepository _playerRepository;
        private readonly ICoachRepository _coachRepository;
        private readonly IMapper _mapper;
        public TeamController(ITeamRepository teamRepository, IPlayerRepository playerRepository, ICoachRepository coachRepository, ISponsorRepository sponsorRepository, ICompetitionTeamRepository competitionTeamRepository, IMapper mapper)
        {
            _coachRepository = coachRepository;
            _playerRepository = playerRepository;
            _teamRepository = teamRepository;
            _sponsorRepository = sponsorRepository;
            _competitionTeamRepository = competitionTeamRepository;
            _mapper = mapper;
        }

        public IActionResult Index(TeamViewModel teamViewModel)
        {
            var teams = _teamRepository.GetAll();
            var teamModels = _mapper.Map<IList<TeamViewModel>>(teams);
            return View(teamModels);
        }

        public IActionResult Add()
        {
            var players = _playerRepository.Get(p => p.TeamId == null);

            ViewData["TeamCoach"] = new SelectList(_coachRepository.GetAll(), "Id", "FullName");
            ViewData["TeamSponsors"] = new SelectList(_sponsorRepository.GetAll(), "Id", "Name");

            var teamViewModel = new TeamViewModel { Players = _mapper.Map<IList<PlayerViewModel>>(players) };

            return View(teamViewModel);
        }

        [HttpPost]
        public IActionResult Add(TeamViewModel teamViewModel)
        {
            var players = _playerRepository.GetAll();

            if (ModelState.IsValid)
            {
                var playersList = new List<Player>();

                foreach (var p in players)
                {
                    if (teamViewModel.SelectedPlayerIds.Contains(p.Id))
                    {
                        playersList.Add(p);
                    }
                }
                var result = _mapper.Map<Team>(teamViewModel);
                result.Players = playersList;
                _teamRepository.Add(result);
                _teamRepository.Save();
                return RedirectToAction("Index");
            }
            teamViewModel.Players = _mapper.Map<List<PlayerViewModel>>(players);
            ViewData["TeamCoach"] = new SelectList(_coachRepository.GetAll(), "Id", "FullName");
            ViewData["TeamSponsors"] = new SelectList(_sponsorRepository.GetAll(), "Id", "Name");

            return View(teamViewModel);
        }

        public IActionResult Edit(int teamId)
        {
            var team = _teamRepository.GetById(teamId);

            var players = _playerRepository.Get(p => p.TeamId == null || p.TeamId == teamId);
            ViewData["TeamCoach"] = new SelectList(_coachRepository.GetAll(), "Id", "FullName");
            ViewData["TeamSponsors"] = new SelectList(_sponsorRepository.GetAll(), "Id", "Name");

            var data = _mapper.Map<TeamViewModel>(team);
            data.Players = _mapper.Map<List<PlayerViewModel>>(players);
            data.SelectedPlayerIds = players.Where(p => p.TeamId == teamId).Select(p => p.Id).ToList();


            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(TeamViewModel teamViewModel)
        {
            var players = _playerRepository.Get(p => p.TeamId == null || p.TeamId == teamViewModel.Id);


            if (ModelState.IsValid)
            {
                foreach (var player in players)
                {
                    if (teamViewModel.SelectedPlayerIds == null || !teamViewModel.SelectedPlayerIds.Contains(player.Id))
                    {
                        player.TeamId = null;
                    }
                    else
                    {
                        player.TeamId = teamViewModel.Id;
                    }


                    _playerRepository.Update(player);
                    _playerRepository.Save();
                }

                _teamRepository.Update(_mapper.Map<Team>(teamViewModel));
                _teamRepository.Save();
                return RedirectToAction("Index");
            }

            ViewData["Players"] = new SelectList(players, "Id", "Name");
            ViewData["TeamCoach"] = new SelectList(_coachRepository.GetAll(), "Id", "FullName");
            ViewData["TeamSponsors"] = new SelectList(_sponsorRepository.GetAll(), "Id", "Name");


            teamViewModel.SelectedPlayerIds = players.Where(p => p.TeamId == teamViewModel.Id).Select(p => p.Id).ToList();

            return View(teamViewModel);
        }

        public IActionResult Delete(int teamId)
        {
            var team = _teamRepository.Get(x => x.Id == teamId).FirstOrDefault();
            if (team != null)
            {
                foreach (var competitionTeam in team.CompetitionTeams)
                {
                    competitionTeam.TeamId = null;
                }
                _teamRepository.Delete(team);
                _teamRepository.Save();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Show(int teamId)
        {
            var players = _playerRepository.Get(p => p.TeamId == teamId);
            var teamViewModel = new TeamViewModel { Players = _mapper.Map<IList<PlayerViewModel>>(players) };

            return View(teamViewModel);
        }

    }
}

SummerCamp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SummerCamp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SummerCamp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SummerCamp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coaches" asp-action="Index">Coaches</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sponsor" asp-action="Index">Sponsors</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="Index">Teams</a>
                        </li>
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CompetitionTeam" asp-action="Index">Competition Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CompetitionMatch" asp-action="Index">Competition Matches</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Competition" asp-action="Index">Competitions</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TeamSponsor" asp-action="Index">Team Sponsors</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SummerCamp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>