SummerCamp/Models/CompetitionTeamViewModel.cs
using SummerCamp.DataModels.Models;

namespace SummerCamp.Models
{
    public class CompetitionTeamViewModel
    {
        public int Id { get; set; }

        public int? CompetitionId { get; set; }

        public int? TeamId { get; set; }

        public int TotalPoints { get; set; }

        public virtual Competition? Competition { get; set; }

        public virtual Team? Team { get; set; }
    }
}

SummerCamp/Controllers/CompetitionTeamController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SummerCamp.DataAccessLayer.Interfaces;
using SummerCamp.DataModels.Models;
using SummerCamp.Models;

namespace SummerCamp.Controllers
{
    public class CompetitionTeamController : Controller
    {
        private readonly ICompetitionTeamRepository _competitionTeamRepository;
        private readonly ITeamRepository _teamRepository;
        private readonly IMapper _mapper;
        public CompetitionTeamController(ICompetitionTeamRepository competitionTeamRepository, ITeamRepository teamRepository, IMapper mapper)
        {
            _competitionTeamRepository = competitionTeamRepository;
            _teamRepository = teamRepository;
            _mapper = mapper;
        }

        public IActionResult Index(CompetitionTeamViewModel competitionTeamViewModel)
        {
            var compTeam = _competitionTeamRepository.GetAll();
            var compTeamModels = _mapper.Map<IList<CompetitionTeamViewModel>>(compTeam);
            return View(compTeamModels);
        }

        public IActionResult Add()
        {
            ViewData["Teams"] = new SelectList(_teamRepository.GetAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Add(CompetitionTeamViewModel competitionTeamViewModel)
        {
            if (ModelState.IsValid)
            {
                _competitionTeamRepository.Add(_mapper.Map<CompetitionTeam>(competitionTeamViewModel));
                _competitionTeamRepository.Save();
                return RedirectToAction("Index");
            }

            return View(competitionTeamViewModel);
        }

        public IActionResult Edit(int competitonTeamId)
        {
            var compTeam = _competitionTeamRepository.GetById(competitonTeamId);
            ViewData["Teams"] = new SelectList(_teamRepository.GetAll(), "Id", "Name");
            var result = _mapper.Map<CompetitionTeamViewModel>(compTeam);
            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(CompetitionTeamViewModel competitionTeamViewModel)
        {
            if (ModelState.IsValid)
            {
                _competitionTeamRepository.Update(_mapper.Map<CompetitionTeam>(competitionTeamViewModel));
                _competitionTeamRepository.Save();
                return RedirectToAction("Index");
            }

            return View(competitionTeamViewModel);
        }

        public IActionResult Delete(int competitonTeamId)
        {
            var compTeam = _competitionTeamRepository.GetById(competitonTeamId);
            _competitionTeamRepository.Delete(compTeam);
            _competitionTeamRepository.Save();
            return RedirectToAction("Index");
        }
    }
}

SummerCamp/Views/CompetitionTeam/Add.cshtml
@using SummerCamp.Models
@model CompetitionTeamViewModel
@{
    ViewData["Title"] = "Add competition team";
}

<form id="myForm" asp-action="Add" method="post" class="needs-validation" novalidate>
    <div class="form-group">
        <label asp-for="TeamId" class="control-label"></label>
        @Html.DropDownList("TeamId", (IEnumerable<SelectListItem>) ViewData["Teams"], "Select a team", new { @class = "form-control" })
        <span asp-validation-for="TeamId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Competition"></label>
        <input asp-for="Competition" class="form-control" />
        <span asp-validation-for="Competition" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TotalPoints"></label>
        <input asp-for="TotalPoints" class="form-control" />
        <span asp-validation-for="TotalPoints" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Edit</button>
</form>

SummerCamp/Views/CompetitionTeam/Edit.cshtml
@using SummerCamp.Models
@model CompetitionTeamViewModel
@{
    ViewData["Title"] = "Edit competition team";
}

<form id="myForm" asp-action="Edit" method="post" class="needs-validation" novalidate>
    <input asp-for="Id" hidden />
    <div class="form-group">
        <label asp-for="Team"></label>
        <input asp-for="Team" class="form-control" />
        <span asp-validation-for="Team" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Competition"></label>
        <input asp-for="Competition" class="form-control" />
        <span asp-validation-for="Competition" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TotalPoints"></label>
        <input asp-for="TotalPoints" class="form-control" />
        <span asp-validation-for="TotalPoints" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Edit</button>
</form>

SummerCamp/Views/CompetitionTeam/Index.cshtml
@using SummerCamp.Models
@model IEnumerable<CompetitionTeamViewModel>
@{
    ViewData["Title"] = "CompetitionTeams";
}
<h1 class="centered-title">CompetitionTeams</h1>
<a asp-controller="CompetitonTeam" asp-action="Add" class="btn btn-primary">Add team to competition</a>
<div class="text-center">
    <div class="table-responsive">
        <table class="table table-bordered table-condensed table-striped table-hover sortable">
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="6">No Records found.</td>
                </tr>
            }
            else
            {
                <thead class="thead-dark">
                    <tr>
                        <th>Team</th>
                        <th>Competition</th>
                        <th>Points</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Team</td>
                            <td>@item.Competition</td>
                            <td>@item.TotalPoints</td>
                            <td>
                                <a asp-action="Edit" asp-controller="CompetitionTeam" asp-route-competitionteamId="@item.Id" class="btn btn-primary">
                                    Edit
                                </a>
                                <a asp-action="Delete" asp-controller="CompetitionTeam" asp-route-competitionteamId="@item.Id" class="btn btn-primary">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            }
        </table>
    </div>
</div>