SummerCamp/Models/CompetitionViewModel.cs
using SummerCamp.DataModels.Models;
using System.ComponentModel.DataAnnotations;

namespace SummerCamp.Models
{
    public class CompetitionViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Va rugam adaugati un nume!")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Va rugam adaugati un numar de echipe!")]
        public int NumbersOfTeams { get; set; }
        [Required(ErrorMessage = "Va rugam adaugati o adresa!")]
        public string Address { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

        public int? SponsorId { get; set; }

        public virtual ICollection<CompetitionMatch>? CompetitionMatches { get; set; } = new List<CompetitionMatch>();
        public virtual IList<CompetitionTeam>? CompetitionTeams { get; set; } = new List<CompetitionTeam>();
        public List<int>? SelectedTeamIds { get; set; }

        public virtual Sponsor? Sponsor { get; set; }
        public virtual IList<Team>? Teams { get; set; }
    }
}

SummerCamp/Controllers/CompetitionController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SummerCamp.DataAccessLayer.Interfaces;
using SummerCamp.DataModels.Models;
using SummerCamp.Models;

namespace SummerCamp.Controllers
{
    public class CompetitionController : Controller
    {
        private readonly ICompetitionRepository _competitionRepository;
        private readonly ISponsorRepository _sponsorRepository;
        private readonly ICompetitionMatchRepository _competitionMatchRepository;
        private readonly ICompetitionTeamRepository _competitionTeamRepository;
        private readonly ITeamRepository _teamRepository;
        private readonly IMapper _mapper;
        public CompetitionController(ICompetitionRepository competitionRepository,
            ICompetitionTeamRepository competitionTeamRepository,
            ICompetitionMatchRepository competitionMatchRepository,
            ISponsorRepository sponsorRepository,
            IMapper mapper,
            ITeamRepository teamRepository)
        {
            _sponsorRepository = sponsorRepository;
            _competitionRepository = competitionRepository;
            _competitionMatchRepository = competitionMatchRepository;
            _competitionTeamRepository = competitionTeamRepository;
            _mapper = mapper;
            _teamRepository = teamRepository;
        }

        public IActionResult Index(CompetitionViewModel competitionViewModel)
        {
            var competition = _competitionRepository.GetAll();
            var competitionModels = _mapper.Map<IList<CompetitionViewModel>>(competition);
            return View(competitionModels);
        }

        public IActionResult Add()
        {
            var teams = _teamRepository.GetAll();
            ViewData["Sponsor"] = new SelectList(_sponsorRepository.GetAll(), "Id", "Name");

            var competitionViewModel = new CompetitionViewModel { Teams = teams };

            return View(competitionViewModel);
        }

        [HttpPost]
        public IActionResult Add(CompetitionViewModel competitionViewModel)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Sponsor"] = new SelectList(_sponsorRepository.GetAll(), "Id", "Name");

                competitionViewModel.Teams = _teamRepository.GetAll();
                return View(competitionViewModel);
            }

            var teams = _teamRepository.GetAll();
            ViewData["Sponsor"] = new SelectList(_sponsorRepository.GetAll(), "Id", "Name");

            var competition = _mapper.Map<Competition>(competitionViewModel);

            competition.CompetitionTeams.Clear();

            foreach (var t in teams)
            {
                if (competitionViewModel.SelectedTeamIds.Contains(t.Id))
                {
                    var competionTeamToAdd = new CompetitionTeam
                    {
                        TeamId = t.Id,
                    };
                    competition.CompetitionTeams.Add(competionTeamToAdd);
                }
            }

            _competitionRepository.Update(competition);
            _competitionRepository.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int competitionId)
        {
            var teams = _teamRepository.GetAll();
            var compTeams = _competitionTeamRepository.Get(c => c.CompetitionId == competitionId);
            var competition = _competitionRepository.Get(c => c.Id == competitionId).FirstOrDefault();
            ViewData["TeamSponsors"] = new SelectList(_sponsorRepository.GetAll(), "Id", "Name");
            var competitionViewModel = _mapper.Map<CompetitionViewModel>(competition);

            var selectedCompetitionTeams = competition.CompetitionTeams.Select(c => c.Team).ToList();

            competitionViewModel.SelectedTeamIds = selectedCompetitionTeams.Select(c => c.Id).ToList();
            competitionViewModel.Teams = teams;



            //_competitionRepository.Update(_mapper.Map<Competition>(competitionViewModel));
            //_competitionRepository.Save();
            return View(competitionViewModel);
        }
        [HttpPost]
        public IActionResult Edit(CompetitionViewModel competitionViewModel)
        {
            ViewData["Sponsor"] = new SelectList(_sponsorRepository.GetAll(), "Id", "Name");
            var teams = _teamRepository.GetAll();

            var notSelectedTeams = _competitionTeamRepository
                .Get(ct => !competitionViewModel.SelectedTeamIds.Contains(ct.TeamId ?? 0)).ToList();

            _competitionTeamRepository.RemoveRange(notSelectedTeams);
            _competitionRepository.Save();
            var alreadySelectedTeams = _competitionTeamRepository
                .Get(ct => ct.CompetitionId == competitionViewModel.Id)
                .Select(ct => ct.Team)
                .ToList();

            if (ModelState.IsValid)
            {
                foreach (var t in competitionViewModel.SelectedTeamIds)
                {
                    if (!alreadySelectedTeams.Select(ct => ct.Id).Contains(t))
                    {
                        var competionTeamToAdd = new CompetitionTeam
                        {
                            CompetitionId = competitionViewModel.Id,
                            TeamId = t,
                        };
                        _competitionTeamRepository.Add(competionTeamToAdd);
                    }
                }

                //_competitionRepository.Update(competition);
                _competitionTeamRepository.Save();
                return RedirectToAction("Index");
            }
            return View(competitionViewModel);
        }

        public IActionResult Delete(int competitionId)
        {
            var competition = _competitionRepository.GetById(competitionId);
            _competitionTeamRepository
                .RemoveRange(_competitionTeamRepository.Get(x => x.CompetitionId == competitionId).ToList());
            _competitionTeamRepository.Save();
            _competitionRepository.Delete(competition);
            _competitionRepository.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int competitionId)
        {
            var matches = _competitionMatchRepository.Get(p => p.CompetitionId == competitionId);
            var competitionViewModel = new CompetitionViewModel { Id = competitionId, CompetitionMatches = matches };

            return View(competitionViewModel);
        }
    }
}

SummerCamp/Controllers/CompetitionMatchController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SummerCamp.DataAccessLayer.Interfaces;
using SummerCamp.DataModels.Models;
using SummerCamp.Models;

namespace SummerCamp.Controllers
{
    public class CompetitionMatchController : Controller
    {
        private readonly ICompetitionRepository _competitionRepository;
        private readonly ITeamRepository _teamRepository;
        private readonly ICompetitionTeamRepository _competitionTeamRepository;
        private readonly ICompetitionMatchRepository _competitionMatchRepository;
        private readonly IMapper _mapper;
        public CompetitionMatchController(ICompetitionMatchRepository competitionMatchRepository, ICompetitionTeamRepository competitionTeamRepository, ICompetitionRepository competitionRepository, ITeamRepository teamRepository, IMapper mapper)
        {
            _competitionTeamRepository = competitionTeamRepository;
            _competitionRepository = competitionRepository;
            _competitionMatchRepository = competitionMatchRepository;
            _teamRepository = teamRepository;
            _mapper = mapper;
        }

        public IActionResult Index(CompetitionMatchViewModel competitionMatchViewModel)
        {
            var competitionMatch = _competitionMatchRepository.Get(c => c.CompetitionId == competitionMatchViewModel.CompetitionId);

            var competitionMatchModels = _mapper.Map<IList<CompetitionMatchViewModel>>(competitionMatch);
            return View(competitionMatchModels);
        }

        public IActionResult Add(int competitionId)
        {
            var teams = _competitionTeamRepository
                .Get(p => p.CompetitionId == competitionId)
                .Select(c => c.Team)
                .ToList();
            // var competitionMatchViewModel = new CompetitionMatchViewModel { AwayTeam = _ };

            var teamList = new SelectList(teams, "Id", "Name");
            ViewData["Teams"] = teamList;
            return View(new CompetitionMatchViewModel()
            {
                CompetitionId = competitionId,


            });
        }

        [HttpPost]
        public IActionResult Add(CompetitionMatchViewModel competitionMatchViewModel)
        {
            if (ModelState.IsValid)
            {
                _competitionMatchRepository.Add(_mapper.Map<CompetitionMatch>(competitionMatchViewModel));
                _competitionMatchRepository.Save();

                return RedirectToAction("Index", competitionMatchViewModel);
            }
            var teams = _competitionTeamRepository
               .Get(p => p.CompetitionId == competitionMatchViewModel.CompetitionId)
               .Select(c => c.Team)
               .ToList();

            var teamList = new SelectList(teams, "Id", "Name");
            ViewData["Teams"] = teamList;
            return View(competitionMatchViewModel);
        }

        public IActionResult Edit(int competitionMatchId)
        {
            var competitionMatch = _competitionMatchRepository.GetById(competitionMatchId);
            var competitionTeams = _competitionTeamRepository
                .Get(x => x.CompetitionId == competitionMatch.CompetitionId)
                .Select(x => x.Team);
            ViewData["Teams"] = new SelectList(competitionTeams, "Id", "Name");
            ViewData["Competition"] = new SelectList(_competitionRepository.GetAll(), "Id", "Name");
            var result = _mapper.Map<CompetitionMatchViewModel>(competitionMatch);
            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(CompetitionMatchViewModel competitionMatchViewModel)
        {
            if (ModelState.IsValid)
            {
                _competitionMatchRepository.Update(_mapper.Map<CompetitionMatch>(competitionMatchViewModel));
                _competitionMatchRepository.Save();
                return RedirectToAction("Index", competitionMatchViewModel);
            }

            return View(competitionMatchViewModel);
        }

        public IActionResult Delete(int competitionMatchId)
        {
            var competitionMatch = _competitionMatchRepository.GetById(competitionMatchId);
            _competitionMatchRepository.Delete(competitionMatch);
            _competitionMatchRepository.Save();
            return RedirectToAction("Details", "Competition", new { competitionId = competitionMatch.CompetitionId });
        }
    }
}

SummerCamp/Views/Competition/Add.cshtml
@using SummerCamp.Models

@model CompetitionViewModel

<form id="myForm" asp-action="Add" method="post" class="needs-validation" asp-controller="Competition" novalidate>
    <input asp-for="Id" hidden />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="NumbersOfTeams"></label>
        <input asp-for="NumbersOfTeams" class="form-control" />
        <span asp-validation-for="NumbersOfTeams" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="StartDate"></label>
        <input asp-for="StartDate" type="date" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-dd")" />
        <span asp-validation-for="StartDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="EndDate"></label>
        <input asp-for="EndDate" type="date" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-dd")" />
        <span asp-validation-for="EndDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="SponsorId" class="control-label"></label>
        @Html.DropDownList("SponsorId", (IEnumerable<SelectListItem>) ViewData["Sponsor"], "Select a sponsor", new { @class = "form-control" })
        <span asp-validation-for="SponsorId" class="text-danger"></span>
    </div>

   <div class="form-group">
        <label asp-for="SelectedTeamIds" class="control-label">Teams</label>
        @{
            var teams = ViewData["Teams"];
            @foreach (var team in Model.Teams)
            {
                <div>
                    <input type="checkbox" id="team@team.Value" name="SelectedTeamIds" value="@team.Id" @(Model.SelectedTeamIds != null && Model.SelectedTeamIds.Contains(Convert.ToInt32(team.Id)) ? "checked" : "")>
                    <label for="team@team.Value">@team.Name</label>
                </div>
            }
        }
        <span asp-validation-for="SelectedTeamIds" class="text-danger"></span>
    </div>


    <button type="submit" class="btn btn-primary">Create</button>
</form>

SummerCamp/Views/Competition/Details.cshtml
@using SummerCamp.Models
@model CompetitionViewModel
@{
    ViewData["Title"] = "Competition";
}
<h1 class="centered-title">Matches of competition @Model.Name</h1>
<input asp-for="Id" hidden />
<a asp-controller="CompetitionMatch" asp-action="Add" asp-route-competitionId="@Model.Id" class="btn btn-primary">Add match</a>
<div class="text-center">
    <div class="table-responsive">
        <table class="table table-bordered table-condensed table-striped table-hover sortable">
            @if (Model.CompetitionMatches?.Count() == 0)
            {
                <tr>
                    <td colspan="6">No Records found.</td>
                </tr>
            }
            else
            {
                <thead class="thead-dark">
                    <tr>
                        <th>Home team</th>
                        <th>Goals</th>
                        <th> </th>
                        <th>Goals</th>
                        <th>Away team</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.CompetitionMatches)
                    {
                        <tr>
                            <td>@item.HomeTeam.Name</td>
                            <td>@item.HomeTeamGoals</td>
                            <td>-</td>
                            <td>@item.AwayTeamGoals</td>
                            <td>@item.AwayTeam.Name</td>

                            <td>
                                <a asp-action="Edit" asp-controller="CompetitionMatch" asp-route-competitionmatchId="@item.Id" class="btn btn-primary">
                                    Edit
                                </a>
                                <a asp-action="Delete" asp-controller="CompetitionMatch" asp-route-competitionmatchId="@item.Id" class="btn btn-primary">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            }
        </table>
    </div>
</div>

SummerCamp/Views/Competition/Edit.cshtml
@using SummerCamp.Models

@model CompetitionViewModel

<form id="myForm" asp-action="Edit" method="post" class="needs-validation" asp-controller="Competition" novalidate>
    <input asp-for="Id" hidden />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="NumbersOfTeams"></label>
        <input asp-for="NumbersOfTeams" class="form-control" />
        <span asp-validation-for="NumbersOfTeams" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="StartDate"></label>
        <input asp-for="StartDate" type="date" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-dd")" />
        <span asp-validation-for="StartDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="EndDate"></label>
        <input asp-for="EndDate" type="date" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-dd")" />
        <span asp-validation-for="EndDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Sponsor" class="control-label"></label>
        @Html.DropDownList("Sponsor", (IEnumerable<SelectListItem>) ViewData["TeamSponsors"], "Select a sponsor", new { @class = "form-control" })
        <span asp-validation-for="Sponsor" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="SelectedTeamIds" class="control-label">Teams</label>
        @{
            var teams = ViewData["Teams"];
            @foreach (var team in Model.Teams)
            {
                <div>
                    <input type="checkbox" id="team@team.Value" name="SelectedTeamIds" value="@team.Id" @(Model.SelectedTeamIds != null && Model.SelectedTeamIds.Contains(Convert.ToInt32(team.Id)) ? "checked" : "")>
                    <label for="team@team.Value">@team.Name</label>
                </div>
            }
        }
        <span asp-validation-for="SelectedTeamIds" class="text-danger"></span>
    </div>

        <button type="submit" class="btn btn-primary">Create</button>
</form>

SummerCamp/Views/Competition/Index.cshtml
@using SummerCamp.Models
@model IEnumerable<CompetitionViewModel>
@{
    ViewData["Title"] = "Competition";
}
<h1 class="centered-title">Competition</h1>
<a asp-controller="Competition" asp-action="Add" class="btn btn-primary">Add competition</a>
<div class="text-center">
    <div class="table-responsive">
        <table class="table table-bordered table-condensed table-striped table-hover sortable">
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="6">No Records found.</td>
                </tr>
            }
            else
            {
                <thead class="thead-dark">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.StartDate)</th>
                        <th>@Html.DisplayNameFor(model => model.EndDate)</th>
                        <th>Name</th>
                        <th>NumbersOfTeams</th>
                        <th>Address</th>
                        <th>Sponsor</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.StartDate.Date.ToShortDateString()</td>
                            <td>@item.EndDate.Date.ToShortDateString()</td>
                            <td>@item.Name</td>
                            <td>@item.NumbersOfTeams</td>
                            <td>@item.Address</td>
                            @if (@item.SponsorId != null)
                            {
                                <td>@item.SponsorId</td>
                            }
                            else
                            {
                                <td>No sponsor</td>
                            }

                            <td>
                                <a asp-action="Edit" asp-controller="Competition" asp-route-competitionId="@item.Id" class="btn btn-primary">
                                    Edit
                                </a>
                                <a asp-action="Details" asp-controller="Competition" asp-route-competitionId="@item.Id" class="btn btn-primary">
                                    Details
                                </a>
                                <a asp-action="Delete" asp-controller="Competition" asp-route-competitionId="@item.Id" class="btn btn-primary">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            }
        </table>
    </div>
</div>